### ISSUE TITLE
No package.json present in repository

### ISSUE THREAD

**Issue by stacygohyunsi** [Vincenttbk/troll_test#1]
**Steps to reproduce:**
1. git clone the repository
2. run `npm install`
3. node index.js

**What happens:** 
- It throws an `Error: Cannot find module 'telegram-node-bot`

**What is expected to happen:** 
- Dependencies should be installed with a package.json file and node index.js should run successfully

**Comment by Vincenttbk** [comment]
Added package.json, issue should be fix now :)

**Comment by stacygohyunsi** [comment]
thanks Vincent!
